# typed: false
# frozen_string_literal: true

# Copyright 2026 Marcus Neves
# SPDX-License-Identifier: MIT

# Generated by hay's brew-formula.sh from the published release archives. Do not hand-edit the
# urls or checksums: they are copied from assets whose provenance attestation was verified.
class Hay < Formula
  desc "Ranked grep for coding agents, with the priors ripgrep deliberately lacks"
  homepage "https://github.com/mneves75/hay"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/mneves75/hay/releases/download/v0.2.0/hay-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "fa3c1bfef5ece324bff40ab2b6c8aaf1abfdde148c67811db213206d1dfa74f6"
    end
    on_intel do
      url "https://github.com/mneves75/hay/releases/download/v0.2.0/hay-v0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "f36e20b10faf00a39b409bf15569a89f715a22faeab77afd619961b2f736b0ee"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mneves75/hay/releases/download/v0.2.0/hay-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "31d6fa1b0a73872d2cea704d2b5b393ab2ee4326c8adda6c0dfef132d3cc26c0"
    end
    on_intel do
      url "https://github.com/mneves75/hay/releases/download/v0.2.0/hay-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "40756d6f3c55e452b8c702419ed6e43eb80296ad04e907784cbf4a7c4055d4f0"
    end
  end

  def install
    bin.install "hay"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  test do
    assert_match "hay #{version}", shell_output("#{bin}/hay --version")

    # The product is the ORDER, so the test asserts the order rather than that the binary runs.
    # Path order would put docs/archive/plan.md first, because "docs" sorts before "src"; hay
    # exists to put the declaration there instead.
    (testpath/"src").mkpath
    (testpath/"docs/archive").mkpath
    (testpath/"src/auth.ts").write("export function validateSession(t) {\n  return t\n}\n")
    (testpath/"docs/archive/plan.md").write("we will call validateSession from the gateway\n")
    output = shell_output("#{bin}/hay -F validateSession .")
    assert_match "src/auth.ts:1:export function validateSession", output.lines.first
    assert_equal 2, output.lines.count

    # Exit 1 is "searched fine, found nothing" — never a failure, and never confused with exit 2.
    shell_output("#{bin}/hay -F no_such_symbol_anywhere .", 1)
  end
end
