# typed: false
# frozen_string_literal: true

# Copyright 2026 Marcus Neves
# SPDX-License-Identifier: MIT

# Generated by hay's brew-formula.sh from the published release archives. Do not hand-edit the
# urls or checksums: they are copied from assets whose provenance attestation was verified.
class Hay < Formula
  desc "Ranked grep for coding agents, with the priors ripgrep deliberately lacks"
  homepage "https://github.com/mneves75/hay"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/mneves75/hay/releases/download/v0.3.1/hay-v0.3.1-aarch64-apple-darwin.tar.gz"
      sha256 "926a0bf6f79942108fc80f9db413c63f36dffa378f66a2fcc96612c585913f7b"
    end
    on_intel do
      url "https://github.com/mneves75/hay/releases/download/v0.3.1/hay-v0.3.1-x86_64-apple-darwin.tar.gz"
      sha256 "958b05c8bb7dcbea800f80856b4e061c9853b8098701d13b17de5dd9e913e6f2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mneves75/hay/releases/download/v0.3.1/hay-v0.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ba248ba0508a311a7d9f2f3c369c9a1927154fc1334a4ce2aa1bb082064f9ded"
    end
    on_intel do
      url "https://github.com/mneves75/hay/releases/download/v0.3.1/hay-v0.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4f8d689f0b5a645c80128ba25d3cd87c4533de14201db07cf5cf45859138c25d"
    end
  end

  def install
    bin.install "hay"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  test do
    assert_match "hay #{version}", shell_output("#{bin}/hay --version")

    # The product is the ORDER, so the test asserts the order rather than that the binary runs.
    # Path order would put docs/archive/plan.md first, because "docs" sorts before "src"; hay
    # exists to put the declaration there instead.
    (testpath/"src").mkpath
    (testpath/"docs/archive").mkpath
    (testpath/"src/auth.ts").write("export function validateSession(t) {\n  return t\n}\n")
    (testpath/"docs/archive/plan.md").write("we will call validateSession from the gateway\n")
    output = shell_output("#{bin}/hay -F validateSession .")
    assert_match "src/auth.ts:1:export function validateSession", output.lines.first
    assert_equal 2, output.lines.count

    # Exit 1 is "searched fine, found nothing" — never a failure, and never confused with exit 2.
    shell_output("#{bin}/hay -F no_such_symbol_anywhere .", 1)
  end
end
