# typed: false
# frozen_string_literal: true

# Copyright 2026 Marcus Neves
# SPDX-License-Identifier: MIT

# Generated by hay's brew-formula.sh from the published release archives. Do not hand-edit the
# urls or checksums: they are copied from assets whose provenance attestation was verified.
class Hay < Formula
  desc "Ranked grep for coding agents, with the priors ripgrep deliberately lacks"
  homepage "https://github.com/mneves75/hay"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/mneves75/hay/releases/download/v0.3.0/hay-v0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "07f6f3ff937f8813a5176a1358a6644fbaede478972d3ba8f558408342872f39"
    end
    on_intel do
      url "https://github.com/mneves75/hay/releases/download/v0.3.0/hay-v0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "d84cde1466ea8111cf176d140d526d43e43f44dcbeb6e59e3795c39639097f95"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mneves75/hay/releases/download/v0.3.0/hay-v0.3.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ec43336151aaff58167f0dd4360c910a07ac7e39bbd00afd5f6ddce29166fa3b"
    end
    on_intel do
      url "https://github.com/mneves75/hay/releases/download/v0.3.0/hay-v0.3.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3ebe46eee434a81c64ae8158bf4ae481e7ea9edbd8c040134f1d4ccbe0e05d87"
    end
  end

  def install
    bin.install "hay"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  test do
    assert_match "hay #{version}", shell_output("#{bin}/hay --version")

    # The product is the ORDER, so the test asserts the order rather than that the binary runs.
    # Path order would put docs/archive/plan.md first, because "docs" sorts before "src"; hay
    # exists to put the declaration there instead.
    (testpath/"src").mkpath
    (testpath/"docs/archive").mkpath
    (testpath/"src/auth.ts").write("export function validateSession(t) {\n  return t\n}\n")
    (testpath/"docs/archive/plan.md").write("we will call validateSession from the gateway\n")
    output = shell_output("#{bin}/hay -F validateSession .")
    assert_match "src/auth.ts:1:export function validateSession", output.lines.first
    assert_equal 2, output.lines.count

    # Exit 1 is "searched fine, found nothing" — never a failure, and never confused with exit 2.
    shell_output("#{bin}/hay -F no_such_symbol_anywhere .", 1)
  end
end
